antomos/donut-dash

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230204161129_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Adds and installs devise gem, adds flashes to application.html.erb, generates user devise model, migrates DB
=> install and create devise user model

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/shared/_navbar.html.erb
Generates devise views.
Sets turbo to false in registration and session views to adapt devise to work with Rails 7.
Creates shared folder with app partial and adds navbar with turb set to false.
=> set turbo to false in views

app/controllers/donuts_controller.rb, app/models/donut.rb, db/migrate/20230204170129_create_donuts.rb, db/schema.rb, test/controllers/donuts_controller_test.rb, test/models/donut_test.rb
create donut model and controller. Still working on the views
=> create donut model and controller

Gemfile, Gemfile.lock, app/controllers/donuts_controller.rb, app/models/donut.rb, app/views/donuts/index.html.erb, config/routes.rb, db/migrate/20230204171351_create_reviews.rb, db/schema.rb
Adds cloudinary and creates donut routes
=> adds cloudinary gem and creates donut routes

app/controllers/orders_controller.rb, app/models/order.rb, db/migrate/20230204174338_create_orders.rb, test/controllers/orders_controller_test.rb, test/models/order_test.rb
Creates model and controller for Order
=> Commit for orders model and controller

config/routes.rb, db/schema.rb, db/seeds.rb
Formats seed file.
Adds test comment to routes.
=> Test branch

db/migrate/20230207192232_change_column_type_for_total_cost.rb, db/schema.rb
Creates migration file to change our total_cost from integer to float.
=> Change column type of total cost

config/routes.rb
=> complete routes just for buyer story

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/account.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Adds account to pages controller and view.
Sets up route to account page.
Adds first_name and last_name to account creation.
Adds first_name and last_name to account edit.
Edits _navbar to link to account page, edit account page, and donuts page.
=> add account page and edit options

app/controllers/donuts_controller.rb, app/models/donut.rb, app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, db/schema.rb, db/seeds.rb
Adds donut views and creates seed
=> Adds donut views and creates seed

Gemfile.lock, app/controllers/reviews_controller.rb, app/models/donut.rb, app/models/review.rb, app/views/donuts/show.html.erb, config/routes.rb, db/migrate/20230207213820_change_associations_of_review.rb, db/schema.rb
Start review controller and views
- Not sure about my .each line
=> PLEASE CHECK VIEW OF DONUT SHOW

app/models/donut.rb, app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, db/migrate/20230204170129_create_donuts.rb, db/schema.rb, db/seeds.rb
I have updated the donut model with the user, adjusted Giulio's line and updated a seed with users and reviews
=> updates donut and seed

db/seeds.rb
=> Revert "seed updated"

app/controllers/donuts_controller.rb, app/views/donuts/index.html.erb, app/views/donuts/new.html.erb, app/views/donuts/show.html.erb, db/migrate/20230204170129_create_donuts.rb, db/schema.rb, db/seeds.rb
-     Added new donut
-     Added the order button to the donut#show
-     Added rating to the donut model
-     Updated seed to recalculate rating after each review, also rating is now between 1 and 5 (0 was rude!)
=> New donut view

app/controllers/donuts_controller.rb, app/models/donut.rb, app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, db/seeds.rb
- Updated donut index and view
- Updated seed (it was the old version)
- New donut is now dynamic (needs a logged user to work otherwise at the moment crashes)
=> updated donut view/index and seed

config/environments/production.rb
set cloudinary production config
=> set cloudinary production config

app/controllers/orders_controller.rb, app/models/donut.rb, app/models/user.rb, app/views/orders/new.html.erb, app/views/orders/show.html.erb, app/views/pages/account.html.erb
Formats order view for created orders
Updates donut order form (new)
Adds orders as buyer and orders as baker to account
=> Add orders to account page

app/views/donuts/show.html.erb, app/views/orders/_form.html.erb, app/views/orders/show.html.erb, db/seeds.rb
=> Latest frontend changes

app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, app/views/orders/_form.html.erb
Donut index and view update 1552
=> Donut index and view update 1508

app/controllers/orders_controller.rb, app/controllers/pages_controller.rb, app/views/orders/_baker_edit_form.html.erb, app/views/pages/account.html.erb, app/views/pages/bakery.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Creates baker page and adds link to user avatar options when logged in and a baker.
Baker page displays all listed baker donuts and option to add new donut.
Displays all order placed by other users in three options:
1. orders placed
2. orders accepted
3. orders marked as complete
Status of order can be set in options 1 and 2. Completion can be changed in options 2 and 3.
Still a lot of updates needed here, but the main part is moving the logic to the back end. 
Will iterate through all baker orders on the back end and set to an item in one of three instance arrays which can be iterated over in the view.
=> Add ability for baker to edit order

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/controllers/donuts_controller.rb, app/javascript/controllers/map_controller.js, app/views/donuts/_info_window.html.erb, app/views/donuts/_marker.html.erb, app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, package.json, yarn.lock
Map working in donut show and styled with the donut as a marker and info on clicking it
=> Map styling

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/donuts_controller.rb, app/controllers/pages_controller.rb, app/javascript/controllers/address_autocomplete_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/views/devise/registrations/new.html.erb, db/seeds.rb
-Map updated with a search field
-Added address to the user form with autocomplete
-Seed with 5 baker and 5 buyers. 
to login Email: baker[number between 0 and 4]@baker.com (i.e baker4@baker.com) or buyer[number between 0 and 4]@buyer.com (i.e. buyer3@buye.com). Password 123456
=> map and address autocomplete done. Seed order not working

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
Fixes navbar dropdown menu issue by removing hidden overflow scss attribute from navbar.
Formats application.html.erb header.
=> Removes sticky from navbar overflow (scss)

app/assets/stylesheets/components/_active_order_card.scss, app/assets/stylesheets/components/_baker_order_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_order_card.scss, app/controllers/donuts_controller.rb, app/controllers/orders_controller.rb, app/controllers/pages_controller.rb, app/views/orders/_baker_edit_form.html.erb, app/views/pages/account.html.erb, app/views/pages/bakery.html.erb, db/seeds.rb
Brings order sort logic to back end
Adds "out for delivery" option
Adds order status cards to user account page
Adds styling for order cards
=> Order confirmation system

app/controllers/pages_controller.rb
Adds method to display all user orders on main account page (as buyer).
Some work needed to make pages controller DRY
=> Make user account page show all dounts they've ordered

app/views/pages/archived.html.erb, app/views/pages/bakery.html.erb
Fix issue with Review seed
Add customer contact info to dropdown box on bakery order card
=> Add customer info to order card

app/controllers/donuts_controller.rb, app/views/donuts/index.html.erb, db/seeds.rb
- Seed update with more reviews, images and bakers have a company name
=> Finalising seed add search to home

app/views/donuts/index.html.erb
Adds tags to unavailable donuts on the index page
=> Adds tags to unavailable donuts on the index page

app/views/donuts/index.html.erb, app/views/donuts/show.html.erb, app/views/pages/home.html.erb, db/seeds.rb
-added tags to donuts in seed
-matched all cards in home, index and view
-added tags icon colors
=> Add tag to donuts in seed

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/registrations/edit.html.erb, app/views/donuts/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
**STYLING:**
- Works on search-bar in the hompage and moves Homer picture to the right.
- Works on search-bar for the donuts index, added same styling.
- Works on some buttons.
- Adds some different fonts for availability of donuts.
=> Styling frontend new

app/views/donuts/show.html.erb, db/migrate/20230204161129_devise_create_users.rb
removed username from show and user model
=> removed username

app/controllers/reviews_controller.rb, app/views/donuts/_info_window.html.erb, app/views/pages/account.html.erb, app/views/pages/bakery.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb, config/routes.rb
Adds new review route, action & view.
Adds link to new review on buyers competed orders (need to style)
Fixes drop down menus in baker orders panel
=> Style dropdowns add review button

app/javascript/controllers/flatpickr_controller.js, app/views/orders/show.html.erb
=> fixed date

app/controllers/donuts_controller.rb, app/views/donuts/index.html.erb
Add basic filter system to index with basic styling
=> Filter tags
